apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: monitoring
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    xpack.security.enabled: true
    xpack.monitoring.enabled: true
    xpack.watcher.enabled: true
    xpack.ml.enabled: false
    xpack.graph.enabled:  false
  ES_JAVA_OPTS: -Xms10000m -Xmx1000m
