apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config-master
  namespace: monitoring
data: 
  NODE_MASTER: "true"
  NODE_DATA: "false"
  NODE_INGEST: "false"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: monitoring
  labels:
    k8s-app: elasticsearch-logging
    version: v6.3
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: elasticsearch-logging
  replicas: 3
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v6.2.5
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v6.2.5
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch-logging
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - elasticsearch-logging
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: jvrodrigues/elasticsearch-xpack:latest
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 20
        volumeMounts:
        - name: elasticsearch-master-data
          mountPath: /data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        env:
        - name: "NODE_MASTER"
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config-master
              key: NODE_MASTER
        - name: "NODE_DATA"
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config-master
              key: NODE_DATA 
        - name: "NODE_INGEST"
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config-master
              key: NODE_INGEST
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-master-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: fast-rbd
      resources:
        requests:
          storage: 4Gi
